
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: course_catalog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - "./database/migrations:/docker-entrypoint-initdb.d" #sync   
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
    ports:
     - "5173:5173" 
    command: ["npm", "run", "dev"]

